In [4]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [ ]:
data = {
    'x': [4, 6, 8, 9],
    'y': [10, 20, 30, 40]
}

In [6]:
df = pd.DataFrame(data)
df 

x   y
0  4  10
1  6  20
2  8  30
3  9  40

In [9]:
X = df - df.mean()
X

x     y
0 -2.75 -15.0
1 -0.75  -5.0
2  1.25   5.0
3  2.25  15.0

In [10]:
cov_matrix = np.cov(X.T)
cov_matrix

array([[  4.91666667,  28.33333333],
       [ 28.33333333, 166.66666667]])

In [11]:
pca = PCA(n_components=2)
x_pca = pca.fit_transform(X)

In [12]:
eigen_values = pca.explained_variance_
eigen_values

array([1.71486144e+02, 9.71895822e-02])

In [13]:
eigen_vectors = pca.components_
eigen_vectors

array([[ 0.16769053,  0.98583969],
       [ 0.98583969, -0.16769053]])

In [14]:
x_pca

array([[-15.24874425,  -0.19570114],
       [ -5.05496633,   0.0990729 ],
       [  5.13881159,   0.39384694],
       [ 15.16489898,  -0.29721871]])